[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[dependencies]
launa-protocol = { path = "../crates/launa-protocol" }
launa-sim = { path = "../crates/launa-sim" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = "0.11"
toml = "0.8"
serialport = "4"
rumqttc = "0.24"
tiny_http = "0.12"
ctrlc = "3"
rand = "0.8"
keyring = "3"
