[package]
name = "launa-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
crc.workspace = true
byteorder.workspace = true

[dev-dependencies]
env_logger = "0.11"

[[test]]
name = "property_tests"
path = "tests/property_tests.rs"

[[test]]
name = "fuzz_tests"
path = "tests/fuzz_tests.rs"
