[package]
name = "launa-hal"
version.workspace = true
edition.workspace = true

[features]
default = ["std"]
std = []

[dependencies]
thiserror.workspace = true

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["executor"] }

[[test]]
name = "hal_tests"
path = "tests/hal_tests.rs"
