[package]
name = "launa-integration-tests"
version.workspace = true
edition.workspace = true

[dependencies]
launa-protocol = { path = "../launa-protocol" }
launa-mqtt = { path = "../launa-mqtt", features = ["std"] }
launa-ota = { path = "../launa-ota" }
launa-sim = { path = "../launa-sim" }
launa-hal = { path = "../launa-hal", features = ["std"] }
launa-core = { path = "../launa-core" }
serde_json = { workspace = true }
