//! Configuration structs for simulated spa responses.
//!
//! These structs define the data returned by the simulator when the controller
//! requests fault logs, filter cycles, information, and configuration. They can
//! be customized via `SpaSim` setter methods to test specific scenarios.

use launa_protocol::fault::FaultCode;

/// Configuration for fault log responses generated by the spa simulator.
///
/// When set on `SpaSim`, the `generate_fault_log_response()` method will produce
/// frames encoding these values instead of the default hardcoded data.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FaultLogConfig {
    /// Total number of faults recorded.
    pub fault_count: u8,
    /// This entry's number.
    pub entry_number: u8,
    /// Fault code identifying the type of fault.
    pub message_code: FaultCode,
    /// How many days ago the fault occurred.
    pub days_ago: u8,
    /// Hour the fault occurred (0-23).
    pub hour: u8,
    /// Minute the fault occurred (0-59).
    pub minute: u8,
    /// Flags (heating mode, temp range).
    pub flags: u8,
    /// Set temperature at time of fault.
    pub set_temperature: u8,
    /// Sensor A temperature at time of fault.
    pub sensor_a_temp: u8,
    /// Sensor B temperature at time of fault.
    pub sensor_b_temp: u8,
}

impl Default for FaultLogConfig {
    fn default() -> Self {
        FaultLogConfig {
            fault_count: 3,
            entry_number: 1,
            message_code: FaultCode::HeaterDry,
            days_ago: 2,
            hour: 14,
            minute: 30,
            flags: 0x04,
            set_temperature: 104,
            sensor_a_temp: 104,
            sensor_b_temp: 102,
        }
    }
}

/// Configuration for filter cycles responses generated by the spa simulator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FilterCyclesConfig {
    /// Filter cycle 1 settings.
    pub filter1: FilterCycleConfig,
    /// Filter cycle 2 settings.
    pub filter2: FilterCycleConfig,
}

/// A single filter cycle's configuration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FilterCycleConfig {
    /// Start hour (0-23).
    pub start_hour: u8,
    /// Start minute (0-59).
    pub start_minute: u8,
    /// Duration hours.
    pub duration_hours: u8,
    /// Duration minutes.
    pub duration_minutes: u8,
    /// Whether this filter cycle is enabled.
    /// Only meaningful for filter 2. Filter 1 is always enabled.
    pub enabled: bool,
}

impl Default for FilterCyclesConfig {
    fn default() -> Self {
        FilterCyclesConfig {
            filter1: FilterCycleConfig {
                start_hour: 8,
                start_minute: 0,
                duration_hours: 4,
                duration_minutes: 0,
                enabled: true,
            },
            filter2: FilterCycleConfig {
                start_hour: 16,
                start_minute: 0,
                duration_hours: 2,
                duration_minutes: 0,
                enabled: true,
            },
        }
    }
}

/// Configuration for information responses generated by the spa simulator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InformationConfig {
    /// Software ID byte 1.
    pub software_id_byte0: u8,
    /// Software ID byte 2.
    pub software_id_byte1: u8,
    /// Software version byte 1.
    pub software_version_byte0: u8,
    /// Software version byte 2.
    pub software_version_byte1: u8,
    /// System model string (8 bytes, ASCII, padded with spaces).
    pub system_model: [u8; 8],
    /// Current setup byte.
    pub current_setup: u8,
    /// Configuration signature byte 1.
    pub config_sig_byte0: u8,
    /// Configuration signature byte 2.
    pub config_sig_byte1: u8,
    /// Configuration signature byte 3.
    pub config_sig_byte2: u8,
    /// Configuration signature byte 4.
    pub config_sig_byte3: u8,
    /// Heater voltage byte.
    pub heater_voltage: u8,
    /// Heater type byte.
    pub heater_type: u8,
    /// DIP switch settings byte 1.
    pub dip_switch_byte0: u8,
    /// DIP switch settings byte 2.
    pub dip_switch_byte1: u8,
}

impl Default for InformationConfig {
    fn default() -> Self {
        let model = *b"BFBP20  ";

        InformationConfig {
            software_id_byte0: 0x64,
            software_id_byte1: 0xDC,
            software_version_byte0: 0x11,
            software_version_byte1: 0x00,
            system_model: model,
            current_setup: 0x01,
            config_sig_byte0: 0x3D,
            config_sig_byte1: 0x12,
            config_sig_byte2: 0x38,
            config_sig_byte3: 0x2E,
            heater_voltage: 0x01,
            heater_type: 0x0A,
            dip_switch_byte0: 0x04,
            dip_switch_byte1: 0x00,
        }
    }
}

/// Configuration for spa configuration responses generated by the spa simulator.
///
/// Maps to the 10-byte payload parsed by `SpaConfig::parse()`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpaConfigConfig {
    /// Raw 10-byte configuration payload.
    pub raw_payload: [u8; 10],
}

impl Default for SpaConfigConfig {
    fn default() -> Self {
        let mut payload = [0u8; 10];
        payload[0] = 0x02;
        payload[1] = 0x02;
        // payload[2] = 0x00 (default)
        // payload[3] = 0x00 (Fahrenheit default)
        payload[5] = 0x0A; // pump1=TwoSpeed, pump2=TwoSpeed
        payload[7] = 0x01; // light1 present
        payload[8] = 0x81; // circ pump present, blower present
        SpaConfigConfig {
            raw_payload: payload,
        }
    }
}
