[package]
name = "launa-app-common"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-hal = { version = "=1.1.0", features = ["esp32", "unstable"] }
esp-radio = { version = "0.18.0", features = ["esp32", "unstable", "wifi", "log-04"] }

embassy-executor = "0.10"
embassy-time = "0.5"
embassy-net = { version = "0.9", features = ["tcp", "dhcpv4", "dhcpv4-hostname", "medium-ethernet", "dns"] }

embedded-io-async = "0.7"

heapless = "0.9"
static_cell = "2"
log = "0.4"

launa-mqtt = { path = "../crates/launa-mqtt", default-features = false }
